/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'MarkPerry' at '3/6/17 10:32 PM' with Gradle 3.1
 *
 * @author MarkPerry, @date 3/6/17 10:32 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
