/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'MarkPerry' at '3/6/17 10:32 PM' with Gradle 3.1
 *
 * @author MarkPerry, @date 3/6/17 10:32 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
